"""
Reader for Campbell Scientific TOB3 Flux_CSIFormat 30-minute data files.

These files are generated by the CR6 datalogger's on-board EasyFlux-DL
processing and contain 30-minute flux averages alongside full meteorological,
net radiation, and soil heat flux observations.

Binary layout (per slot, slot_size = 530 bytes)
------------------------------------------------
  Bytes 0–3   : seconds since 1990-01-01 UTC (LE uint32) — period END time
  Bytes 4–7   : 100-µs sub-second ticks (LE uint32)
  Bytes 8–11  : ring-buffer sequence counter (LE uint32), step = 1
  Bytes 12–527: field data (mixed: ASCII, IEEE4B, BOOL4, FP2)
  Bytes 528–529: 4-byte padding

Timestamps are the END of the 30-minute averaging period.  The reader
converts these to period-start (block_start) by subtracting 30 minutes so
they align with the pipeline's 'timestamp' column.
"""

import csv
import io
import re
import struct
import glob
import os
import numpy as np
import pandas as pd
from datetime import datetime, timezone, timedelta

_CAMPBELL_EPOCH = datetime(1990, 1, 1, tzinfo=timezone.utc)
_FIELD_OFF = 12           # bytes: 8-byte ts + 4-byte ring counter


# ── FP2 decoder ───────────────────────────────────────────────────────────────

def _fp2(raw: int) -> float:
    """
    Convert Campbell FP2 big-endian uint16 to float.

    Per the CR10X manual, Appendix C, p. 252 (also CR1000X / CR6 — same
    Lo-Resolution Final Storage format):
      bit  15        — sign  (0 = +, 1 = −)
      bits 14..13    — decimal locator BC:
                         00 → ×10⁰   (XXXX.)
                         01 → ×10⁻¹  (XXX.X)
                         10 → ×10⁻²  (XX.XX)
                         11 → ×10⁻³  (X.XXX)
      bits 12..0     — 13-bit unsigned mantissa (max 6999 per CSI)

    NaN marker: 0x9FFF (sign=1, BC=00, mantissa=0x1FFF; matches the
    "D,E,F all ones" special-data-type pattern documented on p. 252).
    """
    if raw == 0x9FFF:
        return np.nan
    sign = -1.0 if (raw >> 15) & 1 else 1.0
    bc   = (raw >> 13) & 0x3
    mant = raw & 0x1FFF
    return sign * float(mant) * 10.0 ** (-bc)


# ── Header parser ─────────────────────────────────────────────────────────────

_INTERVAL_UNITS_S = {"SEC": 1, "MIN": 60, "HOUR": 3600, "DAY": 86400}


def _parse_interval(s: str) -> int:
    """
    Parse a TOB3 record-interval string such as ``"30 MIN"`` or ``"1 SEC"``
    and return the value in seconds (0 if unparseable).
    """
    m = re.match(r"\s*(\d+)\s*([A-Za-z]+)", s or "")
    if not m:
        return 0
    n, unit = int(m.group(1)), m.group(2).upper()
    for k, v in _INTERVAL_UNITS_S.items():
        if unit.startswith(k):
            return n * v
    return 0


def _parse_header(raw: bytes):
    """
    Read the 6-line ASCII header.

    Returns
    -------
    header_end  : int             – byte offset where binary data starts
    frame_size  : int             – bytes per TOB3 frame (from table-info line)
    col_names   : list[str]
    dtypes      : list[str]       – one per column, e.g. 'IEEE4B', 'FP2', ...
    interval_s  : int             – record interval in seconds (e.g. 1800)
    """
    lines = []
    pos = 0
    for _ in range(6):
        end = raw.index(b"\r\n", pos)
        lines.append(raw[pos:end].decode("ascii", errors="replace"))
        pos = end + 2
    header_end = pos

    tbl_hdr   = next(csv.reader(io.StringIO(lines[1])))
    col_names = next(csv.reader(io.StringIO(lines[2])))
    dtypes    = next(csv.reader(io.StringIO(lines[5])))

    frame_size = int(tbl_hdr[2])
    interval_s = _parse_interval(tbl_hdr[1])
    return header_end, frame_size, col_names, dtypes, interval_s


# ── Field-size calculator ─────────────────────────────────────────────────────

def _field_size(dtype: str) -> int:
    dtype = dtype.strip()
    if dtype in ("IEEE4B", "BOOL4", "UINT4", "INT4"):
        return 4
    if dtype in ("FP2", "INT2", "UINT2"):
        return 2
    m = re.match(r"ASCII\((\d+)\)", dtype)
    if m:
        return int(m.group(1))
    raise ValueError(f"Unknown dtype: {dtype!r}")


# ── Record decoder ────────────────────────────────────────────────────────────

def _decode_record(raw: bytes, offset: int, dtypes: list) -> list:
    """Decode one field-data record starting at `offset`."""
    vals = []
    off = offset
    for dt in dtypes:
        dt = dt.strip()
        if dt == "IEEE4B":
            v, = struct.unpack_from(">f", raw, off)
            off += 4
        elif dt == "BOOL4":
            v, = struct.unpack_from(">I", raw, off)
            off += 4
        elif dt in ("UINT4", "INT4"):
            fmt = ">I" if dt == "UINT4" else ">i"
            v, = struct.unpack_from(fmt, raw, off)
            off += 4
        elif dt == "FP2":
            v = _fp2(struct.unpack_from(">H", raw, off)[0])
            off += 2
        elif dt == "INT2":
            v, = struct.unpack_from(">h", raw, off)
            off += 2
        else:
            m = re.match(r"ASCII\((\d+)\)", dt)
            n = int(m.group(1))
            v = (raw[off:off + n]
                 .decode("ascii", errors="replace")
                 .rstrip("\x00")
                 .strip())
            off += n
        vals.append(v)
    return vals


# ── Single-file reader ────────────────────────────────────────────────────────

def read_flux_csiformat(filepath: str,
                        period_start: bool = True) -> pd.DataFrame:
    """
    Read one Flux_CSIFormat TOB3 file.

    TOB3 frame layout (per frame):
        Bytes 0–3        minor timestamp (seconds since Campbell epoch, LE u32)
        Bytes 4–7        sub-second (100-µs ticks, LE u32)
        Bytes 8–11       beginning-record number in frame (LE u32)
        Bytes 12…frame_size-4  `recs_per_frame` data records, each of
                               `record_size = sum(field_size)` bytes
        Bytes frame_size-4…frame_size-1  frame footer (validation + count)

    The frame timestamp corresponds to the period-END of the *last*
    record in the frame; records are stored oldest→newest inside the
    frame.  Record k (k=0..N-1) has period-end
    ``frame_ts − (N-1-k) × interval``.

    Parameters
    ----------
    filepath     : path to the .dat file
    period_start : if True (default), subtract one record interval from
                   each record timestamp so it represents the *start* of
                   the averaging period, matching the pipeline's
                   'timestamp' column.

    Returns
    -------
    pd.DataFrame with a UTC-aware 'timestamp' column and all data
    columns.  Every data record present in the file is returned — the
    previous implementation read only the first record per frame and
    silently dropped the rest (visible as "every other row missing" in
    30-min output when frame_size packed 2+ records).
    """
    with open(filepath, "rb") as fh:
        raw = fh.read()

    header_end, frame_size, col_names, dtypes, interval_s = _parse_header(raw)
    record_size = sum(_field_size(dt.strip()) for dt in dtypes)

    FRAME_HDR, FRAME_FOOT = 12, 4
    recs_per_frame = max(1,
        (frame_size - FRAME_HDR - FRAME_FOOT) // max(1, record_size))

    n_frames = (len(raw) - header_end) // frame_size
    if n_frames == 0:
        return pd.DataFrame(columns=["timestamp"] + col_names)

    # ── Frame-header pass: read (secs, usec100, rec_num) for every frame ─
    frame_secs = np.empty(n_frames, dtype=np.uint32)
    frame_usec = np.empty(n_frames, dtype=np.uint32)
    frame_rec  = np.empty(n_frames, dtype=np.uint32)
    _epoch_us  = int(_CAMPBELL_EPOCH.timestamp() * 1e6)
    for i in range(n_frames):
        off = header_end + i * frame_size
        frame_secs[i], = struct.unpack_from("<I", raw, off)
        frame_usec[i], = struct.unpack_from("<I", raw, off + 4)
        frame_rec[i],  = struct.unpack_from("<I", raw, off + 8)

    # ── Frame ordering (detect ring wrap) ────────────────────────────────
    # Within a contiguous run, rec_num increases by `recs_per_frame` per
    # frame.  When the table ring-buffer wraps, rec_num resets; sort by
    # rec_num to recover chronological order.
    expected_step = recs_per_frame
    diffs = np.diff(frame_rec.astype(np.int64))
    if n_frames >= 2 and np.all(diffs == expected_step):
        order = np.arange(n_frames)
    elif n_frames >= 2:
        sorted_diffs = np.diff(np.sort(frame_rec).astype(np.int64))
        if len(sorted_diffs) > 0 and np.all(sorted_diffs == expected_step):
            order = np.argsort(frame_rec, kind="stable")
        else:
            mismatch = np.where(diffs != expected_step)[0]
            end_idx = int(mismatch[0]) + 1 if len(mismatch) else n_frames
            order = np.arange(end_idx)
    else:
        order = np.arange(n_frames)

    # ── Decode every record inside every frame ───────────────────────────
    timestamps  = []
    records     = []
    interval_us = int((interval_s or 1800) * 1_000_000)
    shift_us    = interval_us if period_start else 0

    for fi in order:
        off   = header_end + int(fi) * frame_size
        fsec  = int(frame_secs[fi])
        fusec = int(frame_usec[fi])
        frame_end_us = _epoch_us + fsec * 1_000_000 + fusec * 100
        for k in range(recs_per_frame):
            # period-end of record k = frame_end − (N-1-k)*interval
            ts_us  = frame_end_us - (recs_per_frame - 1 - k) * interval_us
            ts_us -= shift_us
            ts     = np.datetime64(ts_us, "us")
            rec_off = off + FRAME_HDR + k * record_size
            rec = _decode_record(raw, rec_off, dtypes)
            timestamps.append(ts)
            records.append(rec)

    df = pd.DataFrame(records, columns=col_names)
    df.insert(0, "timestamp",
              pd.to_datetime(timestamps, utc=True).tz_convert("UTC"))
    float_cols = [c for c, d in zip(col_names, dtypes) if d.strip() == "IEEE4B"]
    df[float_cols] = df[float_cols].replace([np.inf, -np.inf], np.nan)
    return df


# ── Multi-file collector ──────────────────────────────────────────────────────

def collect_csiformat_files(raw_dir: str) -> list:
    """Return sorted list of Flux_CS(I)Format TOB3 files under raw_dir.

    Matches any filename containing `Flux_CS…Format` where the middle
    block is zero-or-more characters.  Covers the observed variants:
        *_Flux_CSIFormat*.dat
        *_Flux_CSFormat*.dat
        ART_Flux_CSIFormat6.dat
        20800_Flux_CSFormat_11.dat
        BRO_002_Flux_CS_9.dat        (table Flux_CSFormat, filename truncated —
                                      without this the loader finds 0 files and
                                      silently falls back to the gappy AmeriFlux
                                      export)
    """
    pat = re.compile(r"Flux_CS(?:[A-Za-z0-9]*Format|_?\d*\.dat$)", re.IGNORECASE)
    return sorted(
        f for f in glob.glob(
            os.path.join(raw_dir, "**", "*.dat"), recursive=True
        )
        if pat.search(os.path.basename(f))
    )


def collect_notes_files(raw_dir: str) -> list:
    """Return sorted list of Flux_Notes TOB3 files under raw_dir.

    Flux_Notes is the EasyFlux-DL 30-min diagnostics table: rotation angles
    (alpha/beta/gamma), MO_LENGTH / ZL, the frequency-response factors, the
    diagnostic-flag totals, WPL terms and the site-geometry settings
    (latitude / longitude / height_measurement / sonic separations) as the
    logger had them at the time.  Same binary layout as Flux_CS(I)Format.
    """
    pat = re.compile(r"Flux_Notes", re.IGNORECASE)
    return sorted(
        f for f in glob.glob(
            os.path.join(raw_dir, "**", "*.dat"), recursive=True
        )
        if pat.search(os.path.basename(f))
    )


def collect_hydra_files(raw_dir: str) -> list:
    """Return sorted list of HYDRA-format TOB3 files under raw_dir.

    Stevens Hydra / Hydra-Probe loggers record the dielectric-permittivity
    (Ka) output in columns with a `…volt4` suffix.  The binary layout is
    the same Campbell 30-min TOB3 table as the CSI / AmeriFlux files.
    """
    pat = re.compile(r"HYDRA", re.IGNORECASE)
    return sorted(
        f for f in glob.glob(
            os.path.join(raw_dir, "**", "*.dat"), recursive=True
        )
        if pat.search(os.path.basename(f))
    )


def collect_ameriflux_files(raw_dir: str) -> list:
    """Return sorted list of *AmeriFlux* TOB3 files under raw_dir.

    The AmeriFlux-format files carry the same 30-min cadence but with a
    (usually larger) superset of columns — most notably the soil-moisture
    (SWC_*), ground-heat-flux plates (G_*), and full radiation 4-stream
    (SW_IN/SW_OUT/LW_IN/LW_OUT, NETRAD).  Filename matching is case-
    insensitive and allows variants like AmeriFlux, Ameriflux_11, etc.
    """
    pat = re.compile(r"AmeriFlux", re.IGNORECASE)
    return sorted(
        f for f in glob.glob(
            os.path.join(raw_dir, "**", "*.dat"), recursive=True
        )
        if pat.search(os.path.basename(f))
    )


def load_all_csiformat(raw_dir: str,
                       start: pd.Timestamp = None,
                       end:   pd.Timestamp = None,
                       verbose: bool = True) -> pd.DataFrame:
    """
    Read, merge, and deduplicate all Flux_CSIFormat files.

    Parameters
    ----------
    raw_dir : root directory containing the season's *_FLX subdirectories
    start   : optional UTC start filter (inclusive)
    end     : optional UTC end filter   (inclusive)
    verbose : print progress

    Returns
    -------
    pd.DataFrame sorted by timestamp with no duplicate timestamps.
    """
    files = collect_csiformat_files(raw_dir)
    if verbose:
        print(f"Found {len(files)} Flux_CSIFormat files")

    frames = []
    for fp in files:
        try:
            df = read_flux_csiformat(fp, period_start=True)
            if df.empty:
                continue
            if start is not None:
                s = (pd.Timestamp(start).tz_localize("UTC")
                     if pd.Timestamp(start).tzinfo is None else pd.Timestamp(start))
                df = df[df["timestamp"] >= s]
            if end is not None:
                e = (pd.Timestamp(end).tz_localize("UTC")
                     if pd.Timestamp(end).tzinfo is None else pd.Timestamp(end))
                df = df[df["timestamp"] <= e]
            if df.empty:
                continue
            frames.append(df)
            if verbose:
                print(f"  {os.path.basename(fp)}: {len(df)} records "
                      f"({df['timestamp'].iloc[0]} → {df['timestamp'].iloc[-1]})")
        except Exception as e:
            if verbose:
                print(f"  Warning: {os.path.basename(fp)}: {e}")

    if not frames:
        return pd.DataFrame()

    combined = pd.concat(frames, ignore_index=True)
    # Datalogger clock jitter can leave timestamps off the 30-min grid by
    # a few seconds.  Floor to 30-min so they share an exact grid with
    # AmeriFlux fills (avoids the "every other row missing" artefact).
    combined["timestamp"] = combined["timestamp"].dt.floor("30min")
    combined = (combined.sort_values("timestamp")
                        .drop_duplicates("timestamp")
                        .reset_index(drop=True))
    if verbose:
        print(f"  → {len(combined)} unique 30-min CSI records total")
    return combined


def _is_tob_binary(filepath: str) -> bool:
    """
    Sniff first bytes of a .dat file: Campbell TOB1/TOB2/TOB3 binary tables
    always begin with the file-type marker `"TOB3"` (or TOB1/TOB2) as the
    first token on line 1.  Anything else (e.g. `"TIMESTAMP_START",...`) is
    treated as an ASCII CSV export.
    """
    try:
        with open(filepath, "rb") as fh:
            head = fh.read(16)
    except OSError:
        return False
    return head.startswith((b'"TOB1"', b'"TOB2"', b'"TOB3"'))


def read_ameriflux_csv(filepath: str,
                         period_start: bool = True) -> pd.DataFrame:
    """
    Read one AmeriFlux FLUXNET-style CSV file.

    Files of this kind are plain ASCII with a quoted header on line 1 and
    numeric rows that start with `TIMESTAMP_START,TIMESTAMP_END` in the
    `YYYYMMDDHHMM` format, using `"NAN"` as the missing marker.

    We always anchor on `TIMESTAMP_END` (which is what the CSI TOB3 file's
    native `TIMESTAMP` column holds) and convert to period-start via a
    30-min back-shift when `period_start=True`, matching the CSI reader's
    convention.  This avoids a half-hour offset that otherwise makes
    AmeriFlux fills land on the wrong CSI row (the "every other row
    missing" pattern).
    """
    df = pd.read_csv(filepath, na_values=["NAN", "NaN", "-9999", "-9999.0"],
                     low_memory=False)
    # Prefer TIMESTAMP_END (period-end) to match the CSI TOB3 convention;
    # fall back to TIMESTAMP_START only if the file lacks the end column.
    if "TIMESTAMP_END" in df.columns:
        ts_col, is_end = "TIMESTAMP_END", True
    elif "TIMESTAMP_START" in df.columns:
        ts_col, is_end = "TIMESTAMP_START", False
    elif "timestamp" in df.columns:
        ts_col, is_end = "timestamp", False
    else:
        return pd.DataFrame()
    ts = pd.to_datetime(df[ts_col].astype(str), format="%Y%m%d%H%M",
                         errors="coerce", utc=True)
    # Shift period-end → period-start when requested (CSI convention).
    if period_start and is_end:
        ts = ts - pd.Timedelta("30min")
    df = df.drop(columns=[c for c in ("TIMESTAMP_START", "TIMESTAMP_END")
                          if c in df.columns])
    df.insert(0, "timestamp", ts)
    df = df.dropna(subset=["timestamp"])
    # Floor to minute resolution to match the 30-min grid exactly (no
    # sub-minute jitter that would otherwise break reindex-based fills).
    df["timestamp"] = df["timestamp"].dt.floor("min")
    for c in df.columns:
        if c == "timestamp": continue
        df[c] = pd.to_numeric(df[c], errors="coerce")
    return df


def _read_ameriflux_any(filepath: str,
                        period_start: bool = True) -> pd.DataFrame:
    """
    Dispatch to the correct reader based on a cheap file-header sniff so
    we don't spam warnings from the wrong reader when the right one would
    have succeeded.
    """
    if _is_tob_binary(filepath):
        return read_flux_csiformat(filepath, period_start=period_start)
    return read_ameriflux_csv(filepath, period_start=period_start)


def load_all_ameriflux(raw_dir: str,
                       start: pd.Timestamp = None,
                       end:   pd.Timestamp = None,
                       verbose: bool = True) -> pd.DataFrame:
    """
    Read, merge, and deduplicate all AmeriFlux-format files.

    The AmeriFlux export at this site is ASCII CSV with quoted column
    headers and `TIMESTAMP_START`/`TIMESTAMP_END` in `YYYYMMDDHHMM`
    format.  `_read_ameriflux_any` picks the right reader per file
    (CSV first, then TOB3 binary fallback), so both variants coexist.

    AmeriFlux tables typically include SWC_*, NETRAD, SW_IN/OUT,
    LW_IN/OUT, G, SG_1_1_1, soil T profiles at multiple depths, VPD,
    TA/RH profile, USTAR/ZL/MO_LENGTH, FETCH_*, wind components.

    Files that fail to parse are skipped with a warning; the function
    returns an empty DataFrame when no valid files are found.
    """
    files = collect_ameriflux_files(raw_dir)
    if verbose:
        print(f"Found {len(files)} AmeriFlux files")

    frames = []
    for fp in files:
        try:
            df = _read_ameriflux_any(fp, period_start=True)
            if df.empty:
                continue
            if start is not None:
                s = (pd.Timestamp(start).tz_localize("UTC")
                     if pd.Timestamp(start).tzinfo is None else pd.Timestamp(start))
                df = df[df["timestamp"] >= s]
            if end is not None:
                e = (pd.Timestamp(end).tz_localize("UTC")
                     if pd.Timestamp(end).tzinfo is None else pd.Timestamp(end))
                df = df[df["timestamp"] <= e]
            if df.empty:
                continue
            frames.append(df)
            if verbose:
                print(f"  {os.path.basename(fp)}: {len(df)} records "
                      f"({df['timestamp'].iloc[0]} → {df['timestamp'].iloc[-1]})")
        except Exception as e:
            if verbose:
                print(f"  Warning: {os.path.basename(fp)}: {e}")
    if not frames:
        return pd.DataFrame()
    combined = pd.concat(frames, ignore_index=True)
    combined["timestamp"] = combined["timestamp"].dt.floor("30min")
    return (combined.sort_values("timestamp")
                    .drop_duplicates("timestamp")
                    .reset_index(drop=True))


# Default AmeriFlux→CSI rename map — maps FLUXNET-style columns to the
# pre-rename CSI names that the ec_pipeline's merge_datalogger._RENAME
# expects upstream of its SoilWater_*/SW_IN_Wm2/etc. output columns.
AMERIFLUX_RENAME_DEFAULT = {
    # Soil water content (FLUXNET SWC_i_1_1 → CSI SoilWater_i)
    "SWC_1_1_1": "SoilWater_1",
    "SWC_2_1_1": "SoilWater_2",
    "SWC_3_1_1": "SoilWater_3",
    "SWC_4_1_1": "SoilWater_4",
    "SWC_5_1_1": "SoilWater_5",
    # Radiation (AmeriFlux uses bare names; CSI already matches here)
    # "NETRAD": "NETRAD", "SW_IN": "SW_IN", "SW_OUT": "SW_OUT",
    # "LW_IN": "LW_IN", "LW_OUT": "LW_OUT",
    # Soil heat flux (only G is published; storage SG_1_1_1 stays)
    # "G": "G", "SG_1_1_1": "SG_1_1_1",
}


def load_csi_with_fallback(raw_dir: str,
                            start: pd.Timestamp = None,
                            end:   pd.Timestamp = None,
                            ameriflux_fill: bool = True,
                            hydra_fill_swc: bool = True,
                            rename_map: dict = None,
                            hydra_rename_map: dict = None,
                            verbose: bool = True) -> pd.DataFrame:
    """
    Convenience wrapper that chains three loaders.

    Steps (each step is skipped if disabled or no files are found):
      1. Load Flux_CS(I)Format TOB3 files (`load_all_csiformat`).
      2. If `ameriflux_fill=True`, load AmeriFlux-format TOB3 files in
         the same directory and merge them via `fill_from_ameriflux`.
      3. If `hydra_fill_swc=True`, load HYDRA TOB3 files, derive SWC
         from the `*volt4` Ka columns via Topp (1980), and fill SWC
         gaps in the combined frame (`fill_swc_from_hydra`).

    Returns the (possibly augmented) CSI DataFrame.
    """
    csi = load_all_csiformat(raw_dir, start=start, end=end, verbose=verbose)
    if ameriflux_fill:
        amf = load_all_ameriflux(raw_dir, start=start, end=end, verbose=verbose)
        if not amf.empty:
            # Apply the default AmeriFlux→CSI rename map merged with any
            # user-supplied overrides; caller wins on conflicts.
            rm = dict(AMERIFLUX_RENAME_DEFAULT)
            if rename_map:
                rm.update(rename_map)
            if csi.empty:
                csi = amf.rename(columns=rm)
            else:
                csi = fill_from_ameriflux(csi, amf, rename_map=rm,
                                           verbose=verbose)
    if hydra_fill_swc and not csi.empty:
        csi = fill_swc_from_hydra(csi, raw_dir, start=start, end=end,
                                    rename_map=hydra_rename_map,
                                    verbose=verbose)
    return csi


def fill_from_ameriflux(csi_df: pd.DataFrame,
                         amf_df: pd.DataFrame,
                         columns: list = None,
                         rename_map: dict = None,
                         verbose: bool = False) -> pd.DataFrame:
    """
    Fill gaps in a CSI-format DataFrame with values from the AmeriFlux
    DataFrame.  Column names in the AmeriFlux table often differ (e.g.
    `SWC_1_1_1` vs `VW_Avg`, `NETRAD` vs `Rn_Avg`), so callers may supply
    a `rename_map = {amf_name: csi_name}` to align them first.

    Rules:
      * Only columns already present in `csi_df` are filled.  AmeriFlux
        columns that don't exist in `csi_df` are added (if requested via
        `columns=None`).
      * A CSI value is kept when it is finite; otherwise it is replaced
        with the AmeriFlux value at the same timestamp.
      * Returns a new DataFrame; neither input is modified in place.
    """
    if csi_df is None or csi_df.empty:
        return amf_df.copy() if amf_df is not None else pd.DataFrame()
    if amf_df is None or amf_df.empty:
        return csi_df.copy()

    amf = amf_df.copy()
    if rename_map:
        amf = amf.rename(columns=rename_map)

    # Align on timestamp.  Union the two time grids so AmeriFlux-only
    # timestamps (e.g. years that predate the TOB3 Flux_CSIFormat output)
    # are ADDED as new rows, not merely used to gap-fill the existing CSI
    # grid.  Without this, a longer AmeriFlux record silently collapses to
    # the CSI span.
    cdf = csi_df.set_index("timestamp")
    amf_idx = amf.set_index("timestamp")
    full_index = cdf.index.union(amf_idx.index)
    full_index.name = "timestamp"
    cdf = cdf.reindex(full_index)
    adf = amf_idx.reindex(full_index)

    if columns is None:
        # Columns to consider: intersection + new ones from AmeriFlux
        columns = sorted(set(adf.columns))

    out = cdf.copy()
    n_filled = {}
    for col in columns:
        if col not in adf.columns:
            continue
        if col in out.columns:
            target = pd.to_numeric(out[col], errors="coerce")
            src    = pd.to_numeric(adf[col], errors="coerce")
            miss   = ~np.isfinite(target)
            filled = int((miss & src.notna()).sum())
            if filled:
                out[col] = np.where(miss & src.notna(), src, target)
                n_filled[col] = filled
        else:
            # Column missing from CSI entirely → copy from AmeriFlux
            src = pd.to_numeric(adf[col], errors="coerce")
            if src.notna().any():
                out[col] = src.values
                n_filled[col] = int(src.notna().sum())

    if verbose and n_filled:
        print("  AmeriFlux gap-fill:")
        for c, n in sorted(n_filled.items(), key=lambda kv: -kv[1])[:15]:
            print(f"    {c:20s} {n:6d} cells filled")
    return out.reset_index()


# ─────────────────────────────────────────────────────────────────────────────
# HYDRA fallback for SWC (Topp 1980 dielectric → θv conversion)
# ─────────────────────────────────────────────────────────────────────────────

# Topp, Davis & Annan (1980) WRR 16(3), empirical polynomial for θv(Ka):
#   θv = -5.3e-2 + 2.92e-2·Ka - 5.5e-4·Ka² + 4.3e-6·Ka³
TOPP_COEFFS = (-5.3e-2, 2.92e-2, -5.5e-4, 4.3e-6)


def topp_ka_to_theta(ka, clip_range: tuple = (0.0, 0.6)) -> np.ndarray:
    """
    Convert Stevens / Campbell Hydra Ka (dielectric constant) to
    volumetric water content θv [m³ m⁻³] via Topp 1980.

    Values outside the physical range (default 0–0.6 m³ m⁻³) or derived
    from non-finite Ka are returned as NaN.
    """
    a, b, c, d = TOPP_COEFFS
    ka = np.asarray(ka, dtype=float)
    theta = a + b * ka + c * ka ** 2 + d * ka ** 3
    lo, hi = float(clip_range[0]), float(clip_range[1])
    theta = np.where(np.isfinite(ka) & (ka > 0), theta, np.nan)
    theta = np.where((theta >= lo) & (theta <= hi), theta, np.nan)
    return theta


def load_all_hydra(raw_dir: str,
                    start: pd.Timestamp = None,
                    end:   pd.Timestamp = None,
                    verbose: bool = True) -> pd.DataFrame:
    """Read + merge + dedup all HYDRA-format TOB3 files in raw_dir."""
    files = collect_hydra_files(raw_dir)
    if verbose:
        print(f"Found {len(files)} HYDRA files")
    frames = []
    for fp in files:
        try:
            df = read_flux_csiformat(fp, period_start=True)
            if df.empty: continue
            if start is not None:
                s = (pd.Timestamp(start).tz_localize("UTC")
                     if pd.Timestamp(start).tzinfo is None else pd.Timestamp(start))
                df = df[df["timestamp"] >= s]
            if end is not None:
                e = (pd.Timestamp(end).tz_localize("UTC")
                     if pd.Timestamp(end).tzinfo is None else pd.Timestamp(end))
                df = df[df["timestamp"] <= e]
            if df.empty: continue
            frames.append(df)
            if verbose:
                print(f"  {os.path.basename(fp)}: {len(df)} records "
                      f"({df['timestamp'].iloc[0]} → {df['timestamp'].iloc[-1]})")
        except Exception as e:
            if verbose:
                print(f"  Warning: {os.path.basename(fp)}: {e}")
    if not frames:
        return pd.DataFrame()
    combined = pd.concat(frames, ignore_index=True)
    combined["timestamp"] = combined["timestamp"].dt.floor("30min")
    return (combined.sort_values("timestamp")
                    .drop_duplicates("timestamp")
                    .reset_index(drop=True))


def load_swc_from_hydra(raw_dir: str,
                         start: pd.Timestamp = None,
                         end:   pd.Timestamp = None,
                         output_names: list = None,
                         verbose: bool = False) -> pd.DataFrame:
    """
    Derive volumetric water content from Stevens-Hydra Ka columns.

    - Loads every HYDRA TOB3 file via `load_all_hydra`.
    - Columns whose name ends in `volt4` (case-insensitive) are treated
      as Ka (dielectric-constant) readings.
    - Each Ka column is converted via Topp 1980 (which yields θv as
      a decimal fraction m³ m⁻³) and then **scaled by 100** so the
      output matches the CSI `SoilWater_*` convention — volumetric water
      content expressed as a percentage [0–100].  Downstream merge
      aliases the result to `SoilWater_*_pct` and mixes with the
      datalogger-logged percent values directly.
    - Each SWC series is named using `output_names[i]` if supplied,
      else `SWC_{i+1}_1_1_hydra` (fluxnet-style positional indexing).
    - Returns a DataFrame with `timestamp` plus one column per probe.
    """
    hydra = load_all_hydra(raw_dir, start=start, end=end, verbose=verbose)
    if hydra.empty:
        return pd.DataFrame()
    volt4_cols = [c for c in hydra.columns
                  if isinstance(c, str) and c.lower().endswith("volt4")]
    if not volt4_cols:
        if verbose:
            print("  HYDRA: no *volt4 columns found")
        return pd.DataFrame({"timestamp": hydra["timestamp"]})

    out = pd.DataFrame({"timestamp": hydra["timestamp"]})
    default_names = [f"SWC_{i+1}_1_1_hydra" for i in range(len(volt4_cols))]
    names = list(output_names) if output_names else default_names
    if len(names) < len(volt4_cols):
        names = names + default_names[len(names):]

    for name, col in zip(names, volt4_cols):
        ka = pd.to_numeric(hydra[col], errors="coerce").to_numpy(dtype=float)
        # Topp 1980 returns θv as a fraction (0–1); CSI SoilWater columns
        # are in percent (0–100).  Scale so the two are consistent before
        # the merge-with-CSI fill step runs.
        out[name] = topp_ka_to_theta(ka) * 100.0
        if verbose:
            n_ok = int(np.isfinite(out[name]).sum())
            print(f"    {col:24s} → {name:24s}  n_valid={n_ok}")
    return out


def fill_swc_from_hydra(csi_df: pd.DataFrame,
                         raw_dir: str,
                         start: pd.Timestamp = None,
                         end:   pd.Timestamp = None,
                         rename_map: dict = None,
                         verbose: bool = False) -> pd.DataFrame:
    """
    Fill missing SWC cells in a CSI DataFrame with HYDRA-derived values.

    The HYDRA probes produce columns named `SWC_i_1_1_hydra` by default.
    Because the ec_pipeline's datalogger-merge renames CSI `SoilWater_i`
    → `SoilWater_i_pct` downstream, the default rename_map targets the
    *pre-rename* CSI column name (`SoilWater_1`, …, `SoilWater_5`) so
    that HYDRA values flow through `prepare_datalogger_df` and land as
    `SoilWater_i_pct` in the final frame.  Pass a custom `rename_map`
    to target different column names.
    """
    swc = load_swc_from_hydra(raw_dir, start=start, end=end, verbose=verbose)
    if swc.empty or csi_df is None or csi_df.empty:
        return csi_df
    if rename_map is None:
        rename_map = {}
        for c in swc.columns:
            if c == "timestamp": continue
            # SWC_1_1_1_hydra → SoilWater_1   (matches ec_pipeline's
            # merge_datalogger._RENAME source-side names)
            m = re.match(r"SWC_(\d+)_\d+_\d+_hydra", c)
            if m:
                rename_map[c] = f"SoilWater_{int(m.group(1))}"
            else:
                rename_map[c] = c.replace("_hydra", "")
    return fill_from_ameriflux(csi_df, swc,
                                 rename_map=rename_map, verbose=verbose)


# ─────────────────────────────────────────────────────────────────────────────
# TOA5 ASCII telemetry ("datalogger report") CSIFormat files
# ─────────────────────────────────────────────────────────────────────────────
# The station-telemetry archive writes the SAME Flux_CS(I)Format table as the
# card-resident TOB3 files, but as TOA5 ASCII:
#
#     line 1  "TOA5","<station>","CR6","<serial>",...,"Flux_CSIFormat"
#     line 2  quoted column names   (identical to the TOB3 header line 2)
#     line 3  units
#     line 4  aggregation ("Smp"/"Avg"/"Tot")
#     line 5+ data, TIMESTAMP as "YYYY-MM-DD HH:MM:SS"
#
# These files are the *most current* view of a tower — they run to the last
# telemetry poll, whereas the TOB3 cards stop at the last physical site visit.
# They are therefore used to PATCH the card record: card data always wins on a
# shared timestamp, telemetry supplies only the rows the cards never saw.
#
# TIMESTAMP in a Campbell interval table is the period-END (the instant the
# record was stored), which is the same convention `read_flux_csiformat`
# undoes.  We apply the identical back-shift so both sources land on the same
# period-start grid; skipping it would offset telemetry rows by one half-hour
# and produce the classic "every other row missing" interleave.

def read_flux_csiformat_toa5(filepath: str,
                             period_start: bool = True,
                             interval_s: int = None) -> pd.DataFrame:
    """
    Read one TOA5 ASCII Flux_CS(I)Format file.

    Returns a DataFrame with a UTC-aware period-start `timestamp` column and
    the file's native column names — i.e. the same shape `read_flux_csiformat`
    returns for the TOB3 form of the same table, so the two are concatenable.

    `interval_s` defaults to the modal timestamp spacing in the file (falling
    back to 1800 s), so a logger running a non-30-min table still lands on the
    right grid.
    """
    df = pd.read_csv(filepath, skiprows=[0, 2, 3], header=0,
                     na_values=["NAN", "NaN", "-9999", "-9999.0",
                                "INF", "-INF", '"NAN"'],
                     low_memory=False)
    if df.empty or "TIMESTAMP" not in df.columns:
        return pd.DataFrame()

    ts = pd.to_datetime(df["TIMESTAMP"], errors="coerce", utc=True)
    df = df.drop(columns=["TIMESTAMP"])

    if interval_s is None:
        # Modal spacing over the valid timestamps; robust to gaps and to the
        # occasional out-of-order row a telemetry backfill can leave behind.
        d = ts.dropna().sort_values().diff().dt.total_seconds()
        d = d[d > 0]
        interval_s = int(d.mode().iloc[0]) if len(d) else 1800

    if period_start:
        ts = ts - pd.Timedelta(seconds=interval_s)

    # Numeric where the column parses as numeric; string columns (e.g. the
    # `Site` label some programs carry) are left alone rather than blanked.
    for c in df.columns:
        conv = pd.to_numeric(df[c], errors="coerce")
        if conv.notna().sum() >= 0.5 * df[c].notna().sum():
            df[c] = conv.replace([np.inf, -np.inf], np.nan)

    # concat rather than insert: the per-column numeric coercion above leaves
    # the frame heavily fragmented, and insert() on top of that is O(ncols).
    df = pd.concat([ts.rename("timestamp"), df], axis=1)
    df = df.dropna(subset=["timestamp"])
    df["timestamp"] = df["timestamp"].dt.floor("30min" if interval_s == 1800
                                               else f"{interval_s}s")
    return (df.sort_values("timestamp")
              .drop_duplicates("timestamp", keep="last")
              .reset_index(drop=True))


def collect_datalogger_extra_files(paths) -> list:
    """
    Expand `paths` — a str or list of str, each either a file or a directory —
    into a sorted list of candidate CSIFormat telemetry files.

    Directories are scanned NON-recursively for `*CSIFormat*.dat` /
    `*CSFormat*.dat`; explicit file paths are taken verbatim so a caller can
    name one oddly-titled export (`SLM#1_EZFlux_CSIFormat.dat`) directly.
    """
    if paths is None:
        return []
    if isinstance(paths, (str, os.PathLike)):
        paths = [paths]
    pat = re.compile(r"CS[A-Za-z0-9]*Format", re.IGNORECASE)
    out = []
    for p in paths:
        p = os.path.expanduser(str(p))
        if os.path.isdir(p):
            out += [f for f in sorted(glob.glob(os.path.join(p, "*.dat")))
                    if pat.search(os.path.basename(f))]
        elif os.path.exists(p):
            out.append(p)
    # Preserve order, drop repeats.
    seen, uniq = set(), []
    for f in out:
        if f not in seen:
            seen.add(f); uniq.append(f)
    return uniq


def load_datalogger_extra(paths,
                          start: pd.Timestamp = None,
                          end:   pd.Timestamp = None,
                          verbose: bool = True) -> pd.DataFrame:
    """
    Read every telemetry CSIFormat file named by `paths` (TOA5 ASCII or TOB3
    binary — sniffed per file) and return one deduplicated frame.
    """
    files = collect_datalogger_extra_files(paths)
    if verbose:
        print(f"[dl-extra] {len(files)} telemetry CSIFormat file(s)")
    frames = []
    for fp in files:
        try:
            df = (read_flux_csiformat(fp, period_start=True)
                  if _is_tob_binary(fp)
                  else read_flux_csiformat_toa5(fp, period_start=True))
            if df.empty:
                continue
            if start is not None:
                s = pd.Timestamp(start)
                s = s.tz_localize("UTC") if s.tzinfo is None else s.tz_convert("UTC")
                df = df[df["timestamp"] >= s]
            if end is not None:
                e = pd.Timestamp(end)
                e = e.tz_localize("UTC") if e.tzinfo is None else e.tz_convert("UTC")
                df = df[df["timestamp"] <= e]
            if df.empty:
                continue
            frames.append(df)
            if verbose:
                print(f"  {os.path.basename(fp)}: {len(df):,} rows "
                      f"({df['timestamp'].iloc[0]} → {df['timestamp'].iloc[-1]})")
        except Exception as exc:
            if verbose:
                print(f"  Warning: {os.path.basename(fp)}: {exc}")
    if not frames:
        return pd.DataFrame()
    out = pd.concat(frames, ignore_index=True)
    return (out.sort_values("timestamp")
               .drop_duplicates("timestamp", keep="last")
               .reset_index(drop=True))


def patch_csi_with_extra(csi_df: pd.DataFrame,
                         extra_df: pd.DataFrame,
                         verbose: bool = True) -> pd.DataFrame:
    """
    Patch the card-derived CSI record with telemetry rows.

    Card data is authoritative: on a timestamp present in BOTH frames the card
    row is kept untouched, and individual NaN cells in that row are filled from
    telemetry only where the card left them empty.  Timestamps present only in
    the telemetry (typically the tail after the last site visit, plus any
    stretch where a card was lost) are appended.

    Returns a frame sorted by timestamp with a unique 30-min index.
    """
    if extra_df is None or extra_df.empty:
        return csi_df
    if csi_df is None or csi_df.empty:
        if verbose:
            print(f"[dl-extra] no card CSI record — using {len(extra_df):,} "
                  "telemetry rows outright")
        return extra_df

    card = csi_df.set_index("timestamp")
    extra = extra_df.set_index("timestamp")
    # Restrict telemetry to columns the card record also carries, plus any
    # genuinely new ones (a reprogrammed logger can add columns mid-record).
    new_ts = extra.index.difference(card.index)
    n_before = len(card)

    merged = pd.concat([card, extra.loc[new_ts]], axis=0)
    # Cell-level fill on shared timestamps: telemetry only writes where the
    # card is NaN, so a card value is never overwritten.
    shared = card.index.intersection(extra.index)
    n_cells = 0
    if len(shared):
        common_cols = card.columns.intersection(extra.columns)
        block = merged.loc[shared, common_cols]
        filled = block.fillna(extra.loc[shared, common_cols])
        n_cells = int((block.isna() & filled.notna()).to_numpy().sum())
        merged.loc[shared, common_cols] = filled

    merged = merged.sort_index()
    merged = merged[~merged.index.duplicated(keep="first")]
    if verbose:
        print(f"[dl-extra] patched CSI record: {n_before:,} card rows "
              f"+ {len(new_ts):,} telemetry-only rows "
              f"+ {n_cells:,} cells filled → {len(merged):,} rows")
        if len(new_ts):
            # Report the telemetry's OWN max, not the merged max: a card
            # record can carry a corrupt far-future timestamp (BLS_002 has 17
            # such rows, later dropped by the pipeline's range guard), and
            # printing the merged max blamed that garbage on the telemetry.
            print(f"[dl-extra] telemetry extends record to {new_ts.max()}")
    return merged.reset_index()
